# Generated by Django 2.2 on 2019-06-18 16:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190618_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief_content',
            field=models.TextField(null=True, verbose_name='博客摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='博客正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=150, verbose_name='博客标题'),
        ),
    ]
